"use client";
import "./globals.css";
import { umamiConfig } from "./lib/umami";
import localFont from "next/font/local";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import AuthProvider from "./auth/authprovider";
import React from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "BongoExplorer- Find Hidden Gems",
//   description: "Generated by create next app",
// };
export const AuthContext = React.createContext();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          async
          defer
          data-website-id={umamiConfig.websiteId}
          src={umamiConfig.scriptUrl}
          data-do-not-track="true"
          data-cache="true"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader showSpinner={false} />
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
